server:
  port: 9595

spring:
  application:
    name: data-pipeline

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB